### ISSUE TITLE
error running destroy-aio-lab

### ISSUE THREAD

**Issue by hupiper** [cptmorgan-rh/ocp4-aio-vsphere-upi-lab#4]
[admin@jump ocp4-aio-vsphere-upi-lab]$ ansible-playbook destroy-aio-lab.yml -e cluster=true
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] **************************************************************************************************************************************************************************

TASK [get service facts] ******************************************************************************************************************************************************************
skipping: [localhost]

TASK [Restore backup of /etc/resolv.conf] *************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'ansible_facts.services[\"systemd-resolved.service\"].state != \"running\"' failed. The error was: error while evaluating conditional (ansible_facts.services[\"systemd-resolved.service\"].state != \"running\"): 'dict object' has no attribute 'services'\n\nThe error appears to be in '/home/admin/ocp4-aio-vsphere-upi-lab/destroy-aio-lab.yml': line 17, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Restore backup of /etc/resolv.conf\n      ^ here\n"}

PLAY RECAP ********************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by cptmorgan-rh** [comment]
Please check the latest version of the destroy playbook. 

This has been addressed.
